apiVersion: v1
kind: Service
metadata:
    name: my-nginx
    labels:
        run: my-nginx
spec:
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
    selector:
      run: my-nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: my-nginx
spec:
    replicas: 2
    template:
        metadata:
            labels:
                run: my-nginx
        spec:
            containers:
            - name: my-nginx
              image: registry.docker-cn.com/library/nginx:1.13-alpine
              ports:
              - containerPort: 80
